config/routes.rb
Rails.application.routes.draw do
  resources :tx_filter_details
  get 'transacction_type/dynamic', to: 'transacction_type#dynamic'
  resources :tconfigs
  get 'filtering_categorizations/dynamic', to: 'filtering_categorizations#dynamic'
  # get 'tx_sessions/index'

  get 'transacction_type/index', to: 'transacction_type#index'
  resources :transacction_type #'transacction_type/index', to: 'transacction_type#index'
  resources :tx_sessions
  resources :filtering_categorizations
  resources :states, :path => 'testadosxalerta'
  resources :states
  resources :testadosxalerta
  resources :table_orders
  get 'alert_release/index'
  post 'users/expire', to: 'users#expire'

  get 'users/expire', to: 'users#expire'

  get 'user_priority/index'
  get 'user_priority/assignPriority'
  get 'user_priority/assignPriorityPer'
  get 'user_priority/sessionsTran'
  get 'user_priority/groupsPer'

  get 'niv_alertamiento/index'
  get 'con_gen/index'


  filter :locale

  get 'alertc/par4'
  get 'alertc/par3'
  get 'alertc/par2'
  get 'alertc/par1'
  get 'alertn/histTran'
  get 'alertn/transacciones_alerta'
  get 'home/alertaBoton'
  get 'home/pie3'
  get 'home/pie2'
  get 'home/pie1' #, to: 'home#pie1'
  get 'home/contadorSuperior' #, to: 'home#pie1'
  get 'home/totalAlerts'
  get 'home/alertaTransaccional'
  get 'home/alertaPerfiles'
  get 'home/mensajeAlerta'
  get 'home/totalPoratender'
  get 'home/totalAtendidas'

  get 'chart/empty'
  get 'chart/pies'
  get 'chart/dynamic'

  resources 'chart'


  get 'alertn/alertTran', to: 'alertn#alertTran'
  get 'tbitacora/tbitacora'
  get 'tbitaobse/tbitaobse'
  get 'alertn/alertPer', to: 'alertn#alertPer'
  get 'alertc/busqueda', to: 'alertc#busqueda'

  resources :groups

  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :alertn
  resources :alertc
  resources :con_gen
  resources :chart, only: [:index, :dynamic]
  resources :home, only: [:index, :create]
  resources :mail_groups
  resources :gestor_settings


  # get '/:locale' => 'home#index'

  # devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in'}
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/tx_sessions.rb
class TxSessions < ApplicationRecord
end

app/controllers/tx_sessions_controller.rb
class TxSessionsController < ApplicationController
  before_action :set_tx_session, only: [:show, :edit, :update, :destroy]

  # GET /tx_sessions
  # GET /tx_sessions.json
  def index
    @tx_sessions = TxSessions.all


  end

  # GET /tx_sessions/1
  # GET /tx_sessions/1.json
  def show
  end

  # GET /tx_sessions/new
  def new
    @tx_session = TxSessions.new
    @edt = false;

    tFormatos = Tformatos.all
    gon.formatos = tFormatos

    tCampos = Tcamposformato.all
    gon.tCamposFormatos = tCampos

    tLays = Tcamposlay.all
    gon.tCamposLays = tLays
    gon.false = true



  end

  # GET /tx_sessions/1/edit
  def edit
  end

  # POST /tx_sessions
  # POST /tx_sessions.json
  def create
    @tx_session = TxSessions.new(tx_session_params)

    respond_to do |format|
      if @tx_session.save


        @session_id = @tx_session.id
        @tx_session_filter = TxFilter.new

        format.html { redirect_to @tx_session, notice: 'Tx session was successfully created.' }
        format.json { render :show, status: :created, location: @tx_session }
      else
        format.html { render :new }
        format.json { render json: @tx_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tx_sessions/1
  # PATCH/PUT /tx_sessions/1.json
  def update
    respond_to do |format|
      if @tx_session.update(tx_session_params)
        format.html { redirect_to @tx_session, notice: 'Tx session was successfully updated.' }
        format.json { render :show, status: :ok, location: @tx_session }
      else
        format.html { render :edit }
        format.json { render json: @tx_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tx_sessions/1
  # DELETE /tx_sessions/1.json
  def destroy
    @tx_session.destroy
    respond_to do |format|
      format.html { redirect_to tx_sessions_url, notice: 'Tx session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tx_session
      @tx_session = TxSessions.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tx_session_params
      params.require(:tx_sessions).permit(:Lay_id, :Format_id, :Description, :Sessioncolor, :Interval, :Inactive)
    end
end

app/helpers/tx_sessions_helper.rb
module TxSessionsHelper
end

app/views/tx_sessions/edit.html.erb
<%= render 'form', tx_session: @tx_session %>

<%= link_to 'Show', @tx_session %> |
<%= link_to 'Back', tx_sessions_index_path %>

app/views/tx_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row ">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1>Sessions</h1>
        <div class="ibox-content">
          <table class="table text-center table-striped table-condensed toggle-circle-filled tile" data-page-size="8" data-filter=#filter>
            <thead>
              <tr>
                <th class="text-center" >#</th>
                <th class="text-center" >Description</th>
                <th class="text-center" >Count Filters</th>
                <th class="text-center" >New Session Filter</th>
                <th class="text-center" >Inactive</th>
                <th class="text-center" data-hide="phone, table" class="text-center"><%= t('all.edit') %></th>
                <th class="text-center" data-hide="phone, table" class="text-center">Eliminar</th>
              </tr>
            </thead>
            <tbody>
            <% order = 0 %>
              <% @tx_sessions.each do |tx_session| %>
                <% order+=1 %>
                <tr>
                  <td><%= order %></td>
                  <td><%= tx_session.Description %></td>
                  <td><a href="#" class="btn btn-success btn-xs">2</a> </td>
                  <td>
                    <button class="btn btn-success btn-xs  filter" type="button" title="New filter">
                      <i class="fa fa-filter "></i>
                    </button>
                  </td>
                  <td>
                    <% if tx_session.Inactive == "1" %>
                      <% check = "checked" %>
                    <% else %>
                      <% check = "" %>
                    <% end %>

                    <div class="checkbox">
                      <input class="inactive" id=<%= tx_session.Id %> type="checkbox" <%= check %>>
                      <label for="checkbox1">
                      </label>
                    </div>
                  </td>
<!--                  <td><%#= link_to '<button class="btn btn-success btn-xs " type="button"><i class="fa fa-file"></i></button>'.html_safe, tx_session %></td>-->
                  <td><%= link_to '<button class="btn btn-warning btn-xs " type="button"><i class="fa fa-pencil"></i></button>'.html_safe, edit_tx_sessions_path(tx_session) %></td>
<!--                  <td><%#= link_to '<button class="btn btn-danger btn-xs " type="button"><i class="fa fa-trash-o"></i></button>'.html_safe, tx_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
                  <td><button class="btn btn-danger btn-xs eliminarSesion" type="button" id="<%= tx_session.Id %>"><i class="fa fa-trash-o"></i></button></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <br>
          <%= link_to '<button class="btn btn-primary btn-xs" type="button" title="New Session"><i class="fa fa-line-chart"></i> New</button>'.html_safe, new_tx_sessions_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tx_sessions/new.html.erb
<%= render 'form', tx_session: @tx_session %>
<%#= link_to 'Back', tx_sessions_index_path %>

app/views/tx_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lay:</strong>
  <%= @tx_session.Lay_id %>
</p>

<p>
  <strong>Formato:</strong>
  <%= @tx_session.Format_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tx_session.Description %>
</p>

<p>
  <strong>Sessioncolor:</strong>
  <%= @tx_session.Sessioncolor %>
</p>

<p>
  <strong>Interval:</strong>
  <%= @tx_session.Interval %>
</p>

<p>
  <strong>Inactive:</strong>
  <%= @tx_session.Inactive %>
</p>

<%= link_to 'Edit', edit_tx_sessions_path(@tx_session) %> |
<%= link_to 'Back', tx_sessions_index_path %>